#!/bin/ruby

require "./Utilities.rb"
require "./Parameters.rb"
require "./BinDistrib.rb"
require "./PoissonDistrib.rb"

n, k, d = Parameters.parseParameters(ARGV)

if d != 0
    BinDistrib.testBinDistrib(d)
    puts
    PoissonDistrib.testPoissonDistrib(d)
else
    puts("#{k}-combination of a #{n} set:")
    puts(Utilities.combinations(n, k))
end
exit(0)
